FROM python:3.5

WORKDIR /usr/src/app
ADD requirements.txt /usr/src/app
RUN pip install -r requirements.txt

# Install nltk resources
RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader punkt

ADD . /usr/src/app

CMD ["pytest"]
