FROM jupyter/scipy-notebook

WORKDIR /usr/src/app
ADD requirements.txt /usr/src/app
RUN pip install -r requirements.txt

# Install nltk resources
RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader averaged_perceptron_tagger
RUN python -m nltk.downloader wordnet
RUN python -m nltk.downloader vader_lexicon
RUN python -m nltk.downloader wordnet_ic

ENV DATA_PATH=/usr/src/app/tests/data

ADD . /usr/src/app
